name: "CI/CD publish"

on:
  workflow_run:
    workflows: ["CI/CD pull request"]
    branches: [ "main" ]
    types: ["completed"]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish:
    name: "Publish release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Generate GitHub App token"
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: "Mask GitHub App token"
        run: echo "::add-mask::${{ steps.app-token.outputs.token }}"
      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm
      - name: "Install dependencies"
        run: npm ci
      - name: "Build distribution"
        run: npm run package
      - name: "Semantic Release"
        uses: cycjimmy/semantic-release-action@v4.1.1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: "Update major tag"
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          version="${{ steps.semantic.outputs.new_release_version }}"
          major_tag="v${version%%.*}"
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git fetch --tags origin
          git tag -f "${major_tag}" "v${version}"
          git push origin -f "${major_tag}"
