name: "CI/CD pull request"

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  auto:
    runs-on: ubuntu-latest
    steps:
      - name: "Generate GitHub App token"
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: "Mask GitHub App token"
        run: echo "::add-mask::${{ steps.app-token.outputs.token }}"
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false
      - name: "Write date file"
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "$datetime" > date
          cat date
      - name: "Commit and push date file"
        env:
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config user.name "github-app[${{ vars.APP_ID }}]"
          git config user.email "github-app-${{ vars.APP_ID }}@users.noreply.github.com"
          git add date
          git commit -m "chore: update date file"
          target_branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "Pushing to $target_branch"
          git push "https://x-access-token:${APP_TOKEN}@github.com/${{ github.repository }}.git" "HEAD:${target_branch}"
